spring:
  datasource:
    url: jdbc:mysql://49.235.228.58/peiwan?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: wuxiyang
    password: imk944
  redis:
    host: 49.235.228.58
    password: imk94